export const fakeNames = [
  'Mason Phillipps',
  'Benjamin Stephensen',
  'Isabel Callaghan',
  'Julian Gow',
  'Bianca Hagelthorn',
  'Skye Payten',
  'Dominic Oppen',
  'Hunter Burne',
  '# Joel McClemens',
  'Alexandra Verjus',
  'Taylah Pamphlett',
  'Patrick Phocas',
  'Eden Robinson',
  'Bianca Mei',
  'Holly Polini',
  '# Elijah Goold',
  'Bella Steere',
  'Aaron Aird',
  'Sophia Upfield',
  'Tyler Callaway',
  'Sebastian Richardson',
  'Hannah Burnell',
  'Ava Ellery',
  'Gabrielle Girdlestone',
  'Alyssa Darcy',
  'Makayla Pell',
  'Abbey Synnot',
  'Leah Waterhouse',
  'Taylah Petchy',
  'Caitlin Umbagai',
  'Gabriel Cooch',
  'Dylan Wilsmore',
  'Eve Dinah',
  'Jaxon Athaldo',
  'Koby Marie',
  'Audrey Barrallier',
  'Rebecca Boston',
  'Stephanie Grace',
  'Oscar Fereday',
  'Phoebe Wearne',
  'Amelie Littler',
  'Mackenzie Grasby',
  'Joshua Nankervis',
  'Henry Buxton',
  'Alica Salomons',
  'Archie Coull',
  '# Olivia Aikenhead',
  '# Julian Buley',
  '# Scarlett Oakley',
  '# Ellie Seymour',
  'Tayla Cass',
  'Ava Tilly',
  'Will Lewers',
  'Gabriel Grover',
  'Callum Compton',
  'Jorja Fielding',
  'Alicia McSharry',
  'Katie Mundy',
  'Claire Burne',
  'Zac Haire',
  'Cooper Wroblewski',
  'Tyson James',
  'Nicholas Jerger',
  'Toby McCawley',
  'Flynn Macvitie',
  'Hannah Todd',
  'Annabelle Tait',
  'Archer Read',
  'Isaac Bethune',
  'Edward Babbage',
  'Ebony Neighbour',
  'Hunter Gates',
  '# Hugo Traeger',
  '# Jade Dods',
  'Alannah Hilliard',
  'Amber Colquhoun',
  '# Makayla Friend',
  '# Keira Miethke',
  'Brooke Palfreyman',
  'Taylah Lenehan',
  'Leah Hudd',
  'Finn Dunshea',
  'Maya Fysh',
  'Finn Banning',
  'Audrey Winchcombe',
  'Liam Bell',
  'Eden Kennedy',
  'Ryder Baudinet',
  'Dominic Maloney',
  'Will Jacob',
  'Brock Colton',
  'Bethany Baddeley',
  'Alice Hale',
  'Anthony Haddon',
  'Victoria Glennie',
  'Max McGuigan',
  'Jake Wonggu',
  'Eden Lawley',
  'Brooke Gullett',
  'Jacob Mackinolty',
];