name: Deploy vuejs app

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type"
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    permissions:
      contents: write
    needs:
    - deploy-github-pages
    - deploy-cloudflare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: npm
    - name: Configure git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
    - name: Bump version
      id: bump
      run: |
        VERSION=$(npm version ${{ github.event.inputs.bump }} -m "release: %s")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Push changes
      run: git push --follow-tags
    - name: Create GitHub Release
      uses: actions/github-script@v8
      with:
        script: |
          const tag = "${{ steps.bump.outputs.version }}"

          await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: tag,
            name: tag,
            generate_release_notes: true
          })

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: npm
    - run: npm install
    - run: npm run build
    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: dist/

  deploy-github-pages:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-cloudflare:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: npm
    - run: npm install
    - run: IS_WRANGLER=TRUE npm run build
    - name: Build & Deploy Worker
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
